-- AlterTable: Add rotation clamp fields to UnitDefinition
ALTER TABLE "UnitDefinition" ADD COLUMN IF NOT EXISTS "yawClampMin" DOUBLE PRECISION NOT NULL DEFAULT -180;
ALTER TABLE "UnitDefinition" ADD COLUMN IF NOT EXISTS "yawClampMax" DOUBLE PRECISION NOT NULL DEFAULT 180;
ALTER TABLE "UnitDefinition" ADD COLUMN IF NOT EXISTS "pitchClampMin" DOUBLE PRECISION NOT NULL DEFAULT -45;
ALTER TABLE "UnitDefinition" ADD COLUMN IF NOT EXISTS "pitchClampMax" DOUBLE PRECISION NOT NULL DEFAULT 45;

-- AlterTable: Add rotation clamp fields to BuildingDefinition
ALTER TABLE "BuildingDefinition" ADD COLUMN IF NOT EXISTS "yawClampMin" DOUBLE PRECISION NOT NULL DEFAULT -180;
ALTER TABLE "BuildingDefinition" ADD COLUMN IF NOT EXISTS "yawClampMax" DOUBLE PRECISION NOT NULL DEFAULT 180;
ALTER TABLE "BuildingDefinition" ADD COLUMN IF NOT EXISTS "pitchClampMin" DOUBLE PRECISION NOT NULL DEFAULT -45;
ALTER TABLE "BuildingDefinition" ADD COLUMN IF NOT EXISTS "pitchClampMax" DOUBLE PRECISION NOT NULL DEFAULT 45;
